### ISSUE TITLE
Run button 

### ISSUE THREAD

**Issue by Sanjeev238** [sitiom/PluralCrypt#2]
**Current Behavior**
A clear and concise description of what the bug is. If applicable, add screenshots to help explain your problem.

**Expected Behavior**

**Steps to Reproduce**

**Additional context**
![image](https://user-images.githubusercontent.com/65130536/81507223-e073f900-92c9-11ea-8c18-b340549c2222.png)

All buttons not visible. Can not run the program

**Comment by sitiom** [comment]
> **Current Behavior**
> A clear and concise description of what the bug is. If applicable, add screenshots to help explain your problem.
> 
> **Expected Behavior**
> A clear and concise description of what you expected to happen.
> 
> **Steps to Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Go to '...'
> 2. Click on '....'
> 3. Scroll down to '....'
> 4. See error
> 
> **Additional context**
> Add any other context about the problem here.
> ![image](https://user-images.githubusercontent.com/65130536/81507223-e073f900-92c9-11ea-8c18-b340549c2222.png)
> 
> All buttons not visible. Can not run the program
This is a scaling problem. Ill fix it. Can you expand the window on the bottom for a while?

**Comment by sitiom** [comment]
@Sanjeev238
Hi, the latest release should fix it now. Reopen this issue if still encounter any problems.

**Comment by Sanjeev238** [comment]
The Window does not resize from any side.
    On Sunday, May 10, 2020, 08:29:26 PM EDT, sitiom <notifications@github.com> wrote:  
 
 



Current Behavior
A clear and concise description of what the bug is. If applicable, add screenshots to help explain your problem.

Expected Behavior
A clear and concise description of what you expected to happen.

Steps to Reproduce
Steps to reproduce the behavior:
   
   - Go to '...'
   - Click on '....'
   - Scroll down to '....'
   - See error

Additional context
Add any other context about the problem here.


All buttons not visible. Can not run the program
This is a scaling problem. Ill fix it. Can you expand the window on the bottom for a while?

**Comment by moto-ctrl** [comment]
I have exactly same issue - no buttons are visible due to scaling.
I use HiDPI resolution 3200x1800 with 250% scaling

The main window size cannot be changed as it is fixed - can't be resized/maximised. Tested on the latest build 2.0.1.0
