### ISSUE TITLE
Mac version  

### ISSUE THREAD

**Issue by abdogomri** [sitiom/PluralCrypt#5]
**Motivation / Use Case**
is there any way to make a new version of the decryptor for Mac OS ? thank you

**Comment by abdogomri** [comment]
is there any way to make a new version of the decryptor for Mac OS ? thank you

**Comment by sitiom** [comment]
@abdogomri Hi, Use [decrypo](https://github.com/phiberoptick/decrypo) as it is cross-platform.

**Comment by abdogomri** [comment]
there is a problem about this application while installing : fatal:
repository 'https://github.com/ajdnik/homebrew-decrypo/' not found

Error: Failure while executing; `git clone
https://github.com/ajdnik/homebrew-decrypo
/usr/local/Homebrew/Library/Taps/ajdnik/homebrew-decrypo` exited with 128.

the homebrew-decrypo not found , do you know any other way to make it work ?
